# three node (two workers) cluster config
# create cluster command: kind create cluster --config=kind-config.yaml
# delete cluster command: kind delete cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      listenAddress: "127.0.0.1"
      protocol: TCP
  - role: worker
  - role: worker