name: Deploy to GKE

on:
  repository_dispatch:
    types: [trigger-kubernetes-workflow]

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'  # Run only if Terraform Workflow succeeded
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ vars.GCP_GKE_CLUSTER_NAME }} --region ${{ vars.GCP_GKE_CLUSTER_REGION }} --project ${{ vars.GCP_PROJECT_ID }}

      - name: Create Namespace and Configmap
        run: |
          kubectl create -f namespace.yaml
          kubectl config set-context --current --namespace=news-search
          kubectl create configmap nginx-conf --from-file=../frontend/nginx.conf

      - name: Create Secrets
        run: |
          kubectl create secret generic news-api --from-literal=news-api-key=${{ secrets.NEWS_API_KEY }}
          kubectl create secret generic arliai-api --from-literal=arliai-api-key=${{ secrets.ARLIAI_API_KEY }}

      - name: Apply Kubernetes manifests
        run: kubectl apply -f kubernetes/
