name: Deploy to GKE

# trigger the workflow when terraform apply is successful
# with a repository_dispatch event
on:
  repository_dispatch:
    types: [trigger-kubernetes-workflow]

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./kubernetes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Get Credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ vars.GCP_GKE_CLUSTER_NAME }}
          location: ${{ vars.GCP_GKE_CLUSTER_ZONE }}
          use_dns_based_endpoint: 'true'

      - name: Create Namespace and Configmap
        run: |
          kubectl create -f namespace.yaml
          kubectl config set-context --current --namespace=news-search
          kubectl create configmap nginx-conf --from-file=../frontend/nginx.conf

      - name: Create Secrets
        run: |
          kubectl create secret generic news-api --from-literal=news-api-key=${{ secrets.NEWS_API_KEY }}
          kubectl create secret generic arliai-api --from-literal=arliai-api-key=${{ secrets.ARLIAI_API_KEY }}
          kubectl create secret generic groq-api --from-literal=groq-api-key=${{ secrets.GROQ_API_KEY }}

      - name: Apply Kubernetes manifests
        run: kubectl apply -f .
